In [1]:
import numpy as np

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[0]

0

In [15]:
arr[1:5]

array([1, 2, 3, 4])

In [16]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [17]:
arr[:5]

array([0, 1, 2, 3, 4])

In [18]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[0:5] = 100

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
arr = np.arange(0,11)

In [32]:
slice_of_array = arr[0:5]

In [34]:
slice_of_array

array([0, 1, 2, 3, 4])

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
slice_of_array[:] = 99

In [37]:
slice_of_array

array([99, 99, 99, 99, 99])

In [38]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [39]:
arr_copy = arr.copy()

In [40]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [41]:
arr_copy[:] = 100

In [42]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [43]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [57]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
arr_2d.shape

(3, 3)

In [60]:
arr_2d[0]

array([ 5, 10, 15])

In [61]:
arr_2d[2]

array([35, 40, 45])

In [62]:
arr_2d[1,1]

25

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
arr_2d[0,2]

15

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [71]:
arr = np.arange(1,11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [74]:
bool_arr = arr > 4

In [75]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])